### ISSUE TITLE
Use an Azure OpenAI Endpoint

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/cds-ai-codereviewer#2]
We should use the [Azure OpenAI endpoint](https://azure.microsoft.com/en-ca/products/ai-services/openai-service) instead of the [OpenAI API endpoint ](https://platform.openai.com/docs/overview) as the Azure service has been assessed by CCCS for PB data. 

Link to Services in scope on Canada Protected B documentation from MS: https://learn.microsoft.com/en-us/azure/compliance/offerings/offering-canada-protected-b#services-in-scope

List of in scope services: https://www.microsoft.com/licensing/terms/product/PrivacyandSecurityTerms/all
![image](https://github.com/user-attachments/assets/227eba65-cc22-4b97-8e34-171cbf2587c9)

Because the Action will have access to the secrets in the repo this introduces the risk that Protected/Sensitive information will be sent to an un-assessed service. 

I would say this is a required feature change before we start to use this service on any repo that has access to Secrets that may be considered sensitive. Which with how we use organizational secrets in Github is every repo in the cds-snc organization.

**Comment by jimleroyer** [comment]
This is considered complete work with [this PR #3](https://github.com/cds-snc/cds-ai-codereviewer/pull/3).
